<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function https_www_redirects_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.https_www_redirects':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Enables site admins to force a site to use HTTPS or WWW or both.') . '</p>';
      return $output;
    default:
  }
}
